/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConexionDb;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet; //obtener resultados de la consulta
import java.sql.PreparedStatement; //ejecutar la conexion
import java.sql.DriverManager; //establecer conexion con Microsoft
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jonathan
 */
public class DatosPasajeros extends javax.swing.JFrame {

    /**
     * Creates new form DatosPersonales
     */
    public DatosPasajeros() {
        initComponents();
        setLocationRelativeTo(null);
        MostrarDatos();
        MostrarRegistroTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLinea = new javax.swing.JTextField();
        txtAsiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasajero = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtApMaterno = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        txtLinea.setBackground(new java.awt.Color(204, 204, 204));
        txtLinea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAsiento.setBackground(new java.awt.Color(204, 204, 204));
        txtAsiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblPasajero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasajeroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPasajero);

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar Datos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 204, 153));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("Limpiar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(170, 191, 233));
        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Actualizar/ Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PASAJEROS");

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Primer Apellido");

        txtApPaterno.setBackground(new java.awt.Color(204, 204, 204));
        txtApPaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Segundo Apellido");

        btnEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtApMaterno.setBackground(new java.awt.Color(204, 204, 204));
        txtApMaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(194, 194, 249));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar Registro");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Linea");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Asiento");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Origen");

        txtOrigen.setBackground(new java.awt.Color(204, 204, 204));
        txtOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Destino");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("Horario");

        txtHorario.setBackground(new java.awt.Color(204, 204, 204));
        txtHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDestino.setBackground(new java.awt.Color(204, 204, 204));
        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(153, 255, 51));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtLinea, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAsiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(386, 386, 386))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(60, 60, 60))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(btnBuscar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnModificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar))))
                            .addComponent(btnGuardar))
                        .addGap(51, 51, 51)
                        .addComponent(btnNuevo)
                        .addGap(33, 33, 33)
                        .addComponent(btnRegresar)
                        .addGap(82, 82, 82)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(txtAsiento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Falta ingresar el asiento");
            txtAsiento.requestFocus();
        }
        else{
            if(txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Falta ingresar el Nombre");
            txtNombre.requestFocus();    
            }
            else{
                try {
                    Connection con1 = null;
                    ConexionBase conectado= new ConexionBase();
                    con1=conectado.getConnection();
                    Statement st = con1.createStatement();
                    String SQLGuardar ="INSERT INTO Pasajeros1(nombre,apellidoPaterno,apellidoMaterno,linea,asiento,origen,destino,horario)VALUES(?,?,?,?,?,?,?,?)";
                    PreparedStatement pst =con1.prepareCall(SQLGuardar);
                    pst.setString(1,txtNombre.getText());
                    pst.setString(2,txtApPaterno.getText());
                    pst.setString(3,txtApMaterno.getText());
                    pst.setString(4,txtLinea.getText());
                    pst.setInt(5,Integer.parseInt(txtAsiento.getText()));
                    pst.setString(6,txtOrigen.getText());
                    pst.setString(7,txtDestino.getText());
                    pst.setString(8,txtHorario.getText());
                    int n = pst.executeUpdate();
                    pst.close();
                  if(n>0){
                      JOptionPane.showMessageDialog(null,"Datos Guardados Correctamente");
                      limpiar();
                      MostrarDatos();
                      MostrarRegistroTabla();
                      
                  }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Error al Guardar Datos"+e);
                }
            }
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasajeroMouseClicked
        //Sleccionar Registros de la tabla
        try {
            int fila=tblPasajero.getSelectedRow();
            this.txtNombre.setText(tblPasajero.getValueAt(fila, 0).toString());
            this.txtApPaterno.setText(tblPasajero.getValueAt(fila, 1).toString());
            this.txtApMaterno.setText(tblPasajero.getValueAt(fila, 2).toString());
            this.txtLinea.setText(tblPasajero.getValueAt(fila, 3).toString());
            this.txtAsiento.setText(tblPasajero.getValueAt(fila, 4).toString());
            this.txtOrigen.setText(tblPasajero.getValueAt(fila, 5).toString());
            this.txtDestino.setText(tblPasajero.getValueAt(fila, 6).toString());
            this.txtHorario.setText(tblPasajero.getValueAt(fila, 7).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al seleccionar datos "+ e);
        }
  
        
        
    }//GEN-LAST:event_tblPasajeroMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Boton Modificar 
        int fila = this.tblPasajero.getSelectedRow();
        if(fila== -1){
            JOptionPane.showMessageDialog(this,"Para ACTUALIZAR un registro primero debe seleccionarlo");
        }
        else{
            try {
                Connection con2=null;
                ConexionBase conectado=new ConexionBase();
                con2=conectado.getConnection();
                Statement st=con2.createStatement();
                String SQLModifica="UPDATE Pasajeros1 SET nombre=?,apellidoPaterno=?,apellidoMaterno=?,linea=?,origen=?,destino=?,horario=? WHERE asiento=?";
                PreparedStatement pst=con2.prepareStatement(SQLModifica);
                pst.setInt(8,Integer.parseInt(txtAsiento.getText()));
                pst.setString(1,txtNombre.getText());
                pst.setString(2,txtApPaterno.getText());
                pst.setString(3,txtApMaterno.getText());
                pst.setString(4,txtLinea.getText());
                pst.setString(5,txtOrigen.getText());
                pst.setString(6,txtDestino.getText());
                pst.setString(7,txtHorario.getText());
                int s=pst.executeUpdate();
                pst.close();
                
                if(s>0){
                    JOptionPane.showMessageDialog(this,"Datos Actualizados Correctamente");
                    limpiar();
                    MostrarDatos();
                    MostrarRegistroTabla();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Error al actualizar los Datos"+e);
            }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Boton eliminar
        int fila=this.tblPasajero.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Para ELIMINAR un registro primero debes seleccionarlo");
        }
        else{
            int Eliminar=JOptionPane.showConfirmDialog(null,"¿Está seguro de que desea ELIMINAR este registro?","Pregunta",JOptionPane.ERROR_MESSAGE,JOptionPane.YES_NO_OPTION);
            if(Eliminar==JOptionPane.YES_OPTION){
                try {
                    Connection con3=null;
                    ConexionBase Conexion = new ConexionBase();
                    con3=Conexion.getConnection();
                    Statement st= con3.createStatement();
                    String SQLEliminar="DELETE * FROM Pasajeros1 WHERE asiento=?";
                    PreparedStatement pst=con3.prepareStatement(SQLEliminar);
                    
                    pst.setInt(1,Integer.parseInt(txtAsiento.getText()));
                    
                    int n=pst.executeUpdate();
                    if(n>0){
                        JOptionPane.showMessageDialog(this,"Registro Eliminado Correctamente");
                        limpiar();
                        MostrarDatos();
                        MostrarRegistroTabla();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Error al eliminar los Datos");
                }
            }
            
        }
         
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Buscar
       FrmBuscarPasajeros abrir = new FrmBuscarPasajeros();
       abrir.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmPrincipal regresar = new FrmPrincipal();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void MostrarDatos(){
        DefaultTableModel MiTabla =(DefaultTableModel)tblPasajero.getModel();
        String EncabezadoTabla[]={"Nombre","Apellido Paterno","Apellido Materno","Linea","Asiento","Origen","Destino","Horario"};
        MiTabla = new DefaultTableModel(null,EncabezadoTabla);
        tblPasajero.setModel(MiTabla);
                
    }
    
    public void MostrarRegistroTabla(){
        try {
            Connection Conex = null;
            DefaultTableModel lamismatabla= (DefaultTableModel)tblPasajero.getModel();
            ConexionBase conectame = new ConexionBase();
            Conex = conectame.getConnection();
            String Registro[]=new String[8];
            String SQL="SELECT * FROM Pasajeros1";
            Statement sentencia=Conex.createStatement();
            ResultSet rst=sentencia.executeQuery(SQL);
            while(rst.next()){
                
                Registro[0]=rst.getString("nombre");
                Registro[1]=rst.getString("apellidoPaterno");
                Registro[2]=rst.getString("apellidoMaterno");
                Registro[3]=rst.getString("linea");
                Registro[4]=rst.getString("asiento");
                Registro[5]=rst.getString("origen");
                Registro[6]=rst.getString("destino");
                Registro[7]=rst.getString("horario");
                lamismatabla.addRow(Registro);
            }
        tblPasajero.setModel(lamismatabla);
            
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"Tabla error "+ e);
        }
    }
    
    public void limpiar(){
        
        this.txtNombre.setText("");
        this.txtApPaterno.setText("");
        this.txtApMaterno.setText("");
        this.txtLinea.setText("");
        this.txtAsiento.setText("");
        this.txtOrigen.setText("");
        this.txtDestino.setText("");
        this.txtHorario.setText("");
        this.txtAsiento.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPasajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPasajero;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
